// Graph Cache CLI. Every subcommand is backed by real library functionality.
#include "graphcache/cache.hpp"
#include <cstdio>
#include <cstdlib>
#include <string>
namespace { gc::GraphDescriptor make_cpu_desc(std::uint64_t bytes) { gc::GraphDescriptor d; d.backend.kind=gc::BackendKind::Cpu; d.backend.backend_name="cpu"; d.backend.backend_version=1; d.runtime.runtime_version=1; d.runtime.graph_abi=1; d.runtime.kernel_abi=1; d.device.vendor=gc::AcceleratorVendor::Cpu; d.device.architecture="cpu"; gc::GraphNodeDescriptor c; c.node_id=gc::GraphNodeId(1,1); c.category=gc::NodeCategory::MemoryCopy; c.name="copy"; c.memory_bytes=bytes; c.reactive_input_indices={0}; c.reactive_output_indices={0}; c.binding.binding_class=gc::BindingClass::ReplayMutableBinding; c.binding.rebinding_eligible=true; gc::GraphNodeDescriptor k; k.node_id=gc::GraphNodeId(2,2); k.category=gc::NodeCategory::Kernel; k.name="scale"; k.kernel.name="scale"; k.kernel.id_hi=0x5000; k.kernel.id_lo=1; k.kernel.generation=gc::GraphGeneration(1); k.kernel.abi=1; k.kernel.content_digest="k-scale"; k.kernel.contributes_to_correctness=true; k.memory_bytes=bytes; k.shape.dims={static_cast<std::int64_t>(bytes/4)}; k.datatype=gc::Datatype::F32; k.layout=gc::TensorLayout::Contiguous; k.scalar.specialized=true; k.scalar.float_value=2.0f; k.binding.binding_class=gc::BindingClass::ReplayMutableBinding; k.binding.rebinding_eligible=true; k.reactive_input_indices={0}; k.reactive_output_indices={0}; gc::GraphEdgeDescriptor e; e.edge_id=gc::GraphEdgeId(1,1); e.from=c.node_id; e.to=k.node_id; e.kind=gc::DependencyKind::Execution; d.nodes={c,k}; d.edges={e}; d.dependencies={k.kernel}; return d; } }
int main(int argc, char** argv) {
  if (argc < 2) { std::printf("Graph Cache CLI\n  capture [name]\n  list\n  stats\n  snapshot\n  explain\n  invalidate [name]\n  recover\n  serve <port>\n  worker <port> <id>\n"); return 0; }
  const std::string cmd = argv[1];
  if (cmd == "capture") {
    std::string name = argc>2?argv[2]:"cli"; gc::GraphCacheConfig cfg; cfg.backend_kind=gc::BackendKind::Cpu; gc::GraphCache cache(cfg);
    gc::GraphLookupRequest req; req.workload.logical_name=name; req.backend.kind=gc::BackendKind::Cpu; req.backend.backend_name="cpu"; req.runtime.runtime_version=1; req.runtime.graph_abi=1; req.runtime.kernel_abi=1; req.device.vendor=gc::AcceleratorVendor::Cpu; req.device.architecture="cpu"; req.descriptor=make_cpu_desc(64);
    auto r = cache.lookup(req);
    std::printf("capture: hit=%d artifact=%s gen=%llu captured=%d\n", r.hit()?1:0, r.artifact_id.to_string().c_str(), (unsigned long long)r.generation.value, r.capture_started?1:0);
    return 0;
  }
  if (cmd == "list") { gc::GraphCacheConfig cfg; cfg.backend_kind=gc::BackendKind::Cpu; gc::GraphCache cache(cfg); std::printf("graphs=%zu\n", cache.graph_count()); return 0; }
  if (cmd == "stats") { gc::GraphCacheConfig cfg; cfg.backend_kind=gc::BackendKind::Cpu; gc::GraphCache cache(cfg); auto m=cache.metrics(); std::printf("lookups=%llu captures=%llu replays=%llu\n",(unsigned long long)m.lookups,(unsigned long long)m.captures,(unsigned long long)m.replays); return 0; }
  if (cmd == "snapshot") { gc::GraphCacheConfig cfg; cfg.backend_kind=gc::BackendKind::Cpu; gc::GraphCache cache(cfg); auto s=cache.snapshot(); std::printf("graphs_total=%llu active_leases=%llu\n",(unsigned long long)s.graphs_total,(unsigned long long)s.active_leases); return 0; }
  if (cmd == "explain") { gc::GraphCacheConfig cfg; cfg.backend_kind=gc::BackendKind::Cpu; gc::GraphCache cache(cfg); gc::GraphLookupRequest req; req.workload.logical_name="cli"; req.backend.kind=gc::BackendKind::Cpu; req.backend.backend_name="cpu"; req.runtime.runtime_version=1; req.runtime.graph_abi=1; req.runtime.kernel_abi=1; req.device.vendor=gc::AcceleratorVendor::Cpu; req.device.architecture="cpu"; req.descriptor=make_cpu_desc(64); auto r=cache.lookup(req); auto ex=cache.explain(r); std::printf("explain: %s\n", ex.text.c_str()); return 0; }
  if (cmd == "invalidate") { std::string name=argc>2?argv[2]:"cli"; gc::GraphCacheConfig cfg; cfg.backend_kind=gc::BackendKind::Cpu; gc::GraphCache cache(cfg); gc::GraphLookupRequest req; req.workload.logical_name=name; req.backend.kind=gc::BackendKind::Cpu; req.backend.backend_name="cpu"; req.runtime.runtime_version=1; req.runtime.graph_abi=1; req.runtime.kernel_abi=1; req.device.vendor=gc::AcceleratorVendor::Cpu; req.device.architecture="cpu"; req.descriptor=make_cpu_desc(64); [[maybe_unused]] auto _r0=cache.lookup(req); gc::InvalidationRequest inv; inv.scope=gc::InvalidationScope::ByWorkload; inv.workload.logical_name=name; auto res=cache.invalidate(inv); std::printf("invalidated=%zu\n", res.invalidated); return 0; }
  if (cmd == "recover") { gc::GraphCacheConfig cfg; cfg.backend_kind=gc::BackendKind::Cpu; cfg.enable_persistence=true; cfg.persistence_dir="gc-cli-persist"; gc::GraphCache cache(cfg); auto r=cache.recover(); std::printf("recover ok=%d\n", r.ok()?1:0); return 0; }
  if (cmd == "serve" || cmd == "worker") { std::string exe=cmd=="serve"?"gc-coordinator":"gc-worker"; std::string a; for(int i=2;i<argc;++i) a+=std::string(" ")+argv[i]; int rc=std::system(("start /B "+exe+a).c_str()); std::printf("%s: launched (rc=%d)\n", cmd.c_str(), rc); return 0; }
  std::printf("unknown command '%s'\n", cmd.c_str()); return 1;
}
